import { BeetleEntry, GenerationValue } from "./beetle";

export const createId = () => Math.random().toString(36).substring(2, 11);
// The `today` function was moved to `lib/utils.ts` to unify date handling.
export const today = () => new Date().toISOString().split('T')[0];

export const formatDate = (date?: string) => {
  if (!date || date === "-") return "-";
  return date.split('T')[0];
};

export const formatGeneration = (gen: GenerationValue) => {
  if (!gen || gen.primary === "-") return "-";
  const count = gen.count || "";
  const secondary = gen.secondary !== "-" ? `(${gen.secondary})` : "";
  return `${gen.primary}${count}${secondary}`;
};

export const isSpawnSetFinished = (entry: any) => {
  if (entry.type !== "産卵セット") return false;
  return !!(entry.setEndDate && entry.setEndDate !== "-");
};

export const getShortenedSciName = (sciName: string) => {
  if (!sciName) return "";
  const parts = sciName.trim().split(/\s+/);
  return parts
    .map((p, i) => (i === 0 ? p[0]?.toUpperCase() : p[0]?.toLowerCase()) || "")
    .join("");
};

export const parseAmbiguousDate = (str: string): Date | null => {
  if (!str || str === "-") return null;
  const d = new Date(str);
  return isNaN(d.getTime()) ? null : d;
};

/**
 * 自動採番ロジック
 * 1. テンプレートから「連番の形式（区切り文字と桁数）」を動的に解析。
 * 2. 既存の管理名がある場合、末尾の古い連番を除去。
 * 3. 既存名が自動生成されたもの（日付等）である場合、現在のテンプレートで再生成。
 * 4. 既存名がカスタム名である場合、その名前をベースにテンプレート通りの連番を付与。
 */
export function generateUniqueMName(
  date: string,
  sciName: string,
  entries: BeetleEntry[],
  type: string,
  format: string,
  currentName?: string,
  metadata?: { japaneseName?: string; locality?: string; generation?: string }
) {
  const d = date ? new Date(date) : new Date();
  const yyyy = String(d.getFullYear());
  const yy = yyyy.slice(-2);
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');

  // テンプレートから連番部分（_NN, -NNN等）を解析
  const serialMatch = format.match(/([_-]?)(N+)/);
  const separator = serialMatch?.[1] ?? "_";
  const padding = serialMatch?.[2].length ?? 2;
  const serialPlaceholder = serialMatch?.[0] ?? "_NN";

  const resolveTemplate = (tpl: string) => {
    let r = tpl.replace(/YYYY/g, yyyy).replace(/YY/g, yy).replace(/MM/g, mm).replace(/DD/g, dd);
    r = r.replace(/{SHORT_SCI}/g, getShortenedSciName(sciName));
    r = r.replace(/{JPN}/g, metadata?.japaneseName || "").replace(/{LOC}/g, metadata?.locality || "").replace(/{GEN}/g, metadata?.generation || "");
    return r;
  };

  const isAutoGenerated = (s: string) => {
    // 日付パターン(6-8桁)やテンプレートタグが含まれるか判定
    return /\d{4,8}/.test(s) || s.includes("{") || s.includes("}") || s.includes("NN");
  };

  let effectiveName = currentName;
  let prefix: string;

  if (effectiveName && effectiveName.trim() !== "" && effectiveName !== "-") {
    // 末尾の既存連番（_01, -1等）を除去してベース名を抽出
    const base = effectiveName.replace(/([_-]?\d+)+$/, "").replace(/NN/g, "");

    // ベースが自動生成されたものならテンプレートで作り直す。カスタム名ならそれを維持。
    if (isAutoGenerated(base)) {
      prefix = resolveTemplate(format).replace(serialPlaceholder, "");
    } else {
      prefix = base;
    }
  } else {
    prefix = resolveTemplate(format).replace(serialPlaceholder, "");
  }

  prefix = prefix.replace(/[_-]{2,}/g, "_").replace(/^[_-]+|[_-]+$/g, "");

  let count = 1;
  while (true) {
    const nn = String(count).padStart(padding, '0');
    const candidate = `${prefix}${separator}${nn}`;
    const collision = entries.some(e => e.managementName === candidate && e.type === type);
    if (!collision) return candidate;
    count++;
    if (count > 999) return `${candidate}_overflow`;
  }
}

export const splitDate = (dateStr: string) => {
  if (!dateStr || dateStr === "-") return { year: "-", month: "-", day: "-" };
  const [y, m, d] = dateStr.split("-");
  return { year: y || "-", month: m || "-", day: d || "-" };
};

export const buildDateFromParts = (y: string, m: string, d: string) => {
  if (y === "-" || m === "-" || d === "-") return "-";
  return `${y}-${m.padStart(2, '0')}-${d.padStart(2, '0')}`;
};

export const createDateOptions = () => {
  const years = ["-", ...Array.from({ length: 11 }, (_, i) => String(2020 + i))];
  const months = ["-", ...Array.from({ length: 12 }, (_, i) => String(i + 1).padStart(2, '0'))];
  const days = ["-", ...Array.from({ length: 31 }, (_, i) => String(i + 1).padStart(2, '0')), "上", "中", "下"];
  return { years, months, days };
};

export const daysBetween = (date1: string, date2: string): number | null => {
  if (!date1 || date1 === "-" || !date2 || date2 === "-") return null;
  const d1 = new Date(date1);
  const d2 = new Date(date2);
  if (isNaN(d1.getTime()) || isNaN(d2.getTime())) return null;
  const diffTime = Math.abs(d2.getTime() - d1.getTime());
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24));
};

export const addDays = (date: string, days: number): string => {
  if (!date || date === "-") return "-";
  const d = new Date(date);
  if (isNaN(d.getTime())) return "-";
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};